# Generated by Django 3.2.8 on 2021-11-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_publication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
