# Generated by Django 3.2.8 on 2021-11-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_publication_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
