# Generated by Django 3.2.8 on 2021-12-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211208_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('-publishedDate',)},
        ),
    ]
