# Generated by Django 3.2.8 on 2021-11-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20211121_2247'),
        ('posts', '0006_alter_rating_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
    ]
