# Generated by Django 3.2.8 on 2021-11-25 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_staff_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_article_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publisher',
            new_name='institution',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.article'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.article'),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250, unique=True)),
                ('file', models.FileField(upload_to=posts.models.upload_to)),
                ('abstract', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('publishedDate', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('authors', models.TextField()),
                ('category', models.ManyToManyField(blank=True, to='posts.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.archive'),
        ),
        migrations.AddField(
            model_name='rating',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.archive'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'article', 'archive')},
        ),
    ]
