# Generated by Django 3.2.8 on 2021-11-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20211121_2247'),
        ('posts', '0008_auto_20211125_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='workspace',
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspaceuploadedfile'),
        ),
    ]
