# Generated by Django 3.2.8 on 2021-11-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_staff_department'),
        ('posts', '0010_auto_20211125_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='article',
            name='institution',
        ),
        migrations.AddField(
            model_name='archive',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.department'),
        ),
        migrations.AddField(
            model_name='article',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.department'),
        ),
    ]
