# Generated by Django 3.2.8 on 2021-12-01 02:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_alter_classroommember_status'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classrooms.classroommember'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Members of this workspace.', related_name='workspace_members', to='classrooms.ClassroomMember'),
        ),
        migrations.AddField(
            model_name='workspacefolder',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspacefolder',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='isnotamember',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
