# Generated by Django 3.2.8 on 2021-11-30 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('workspaces', '0002_remove_workspace_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroommember'),
        ),
    ]
