# Generated by Django 3.2.8 on 2021-11-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspacefolder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacefolder',
            name='user',
        ),
    ]
