# Generated by Django 3.2.8 on 2021-12-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20211201_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='leader',
        ),
    ]
