# Generated by Django 3.2.8 on 2021-11-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_initial'),
        ('workspaces', '0003_remove_workspacefolder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacefolder',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces_workspacefolder_related', related_query_name='workspaces_workspacefolders', to='institutions.institution'),
        ),
    ]
