# Generated by Django 3.2.8 on 2021-11-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('workspaces', '0003_alter_member_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='student',
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroommember'),
        ),
        migrations.DeleteModel(
            name='MemberType',
        ),
    ]
