# Generated by Django 3.2.8 on 2021-12-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_alter_classroom_creator'),
        ('workspaces', '0003_remove_workspace_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classrooms.classroommember'),
        ),
    ]
