# Generated by Django 3.2.8 on 2021-11-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20211121_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_members', to='workspaces.workspace'),
        ),
    ]
