# Generated by Django 3.2.8 on 2021-11-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_alter_member_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace'),
        ),
    ]
