# Generated by Django 3.2.8 on 2021-12-03 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_alter_classroom_creator'),
        ('workspaces', '0005_auto_20211202_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroommember'),
        ),
    ]
