# Generated by Django 3.2.8 on 2021-12-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
