# Generated by Django 3.2.8 on 2021-11-28 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0007_workspace_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacequillfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.upload_to),
        ),
        migrations.AddField(
            model_name='workspacequillfile',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspaceuploadedfile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkspaceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('tags', models.CharField(blank=True, max_length=10, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=files.models.upload_to)),
                ('content', models.TextField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces_workspacefile_related', related_query_name='workspaces_workspacefiles', to='workspaces.workspacefolder')),
            ],
            options={
                'unique_together': {('name', 'folder')},
            },
        ),
    ]
