# Generated by Django 3.2.8 on 2021-11-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211117_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='cover',
            new_name='profileCover',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='image',
            new_name='profileImage',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
