# Generated by Django 3.2.8 on 2021-11-14 03:22

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('file', models.FileField(upload_to=articles.models.upload_to)),
                ('abstract', models.TextField()),
                ('author', models.TextField()),
                ('publisher', models.TextField()),
                ('publishedDate', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
    ]
