# Generated by Django 3.2.8 on 2021-12-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.publication'),
        ),
    ]
