# Generated by Django 3.2.8 on 2021-12-01 02:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_initial'),
        ('libraries', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryitem',
            old_name='content',
            new_name='publication',
        ),
        migrations.RenameField(
            model_name='libraryitem',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='libraryitem',
            unique_together={('user', 'publication')},
        ),
    ]
