# Generated by Django 3.2.8 on 2021-11-11 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomresourceuploadedfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_classroomresourceuploadedfile_related', related_query_name='classrooms_classroomresourceuploadedfiles', to='classrooms.classroomresourcefolder'),
        ),
        migrations.AddField(
            model_name='classroomresourcequillfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_classroomresourcequillfile_related', related_query_name='classrooms_classroomresourcequillfiles', to='classrooms.classroomresourcefolder'),
        ),
        migrations.AddField(
            model_name='classroomresourcefolder',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_resource_folder', to='classrooms.resource'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('student', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='classroomresourceuploadedfile',
            unique_together={('name', 'folder')},
        ),
        migrations.AlterUniqueTogether(
            name='classroomresourcequillfile',
            unique_together={('name', 'folder')},
        ),
        migrations.AlterUniqueTogether(
            name='classroomresourcefolder',
            unique_together={('name', 'resource')},
        ),
    ]
