# Generated by Django 3.2.8 on 2021-11-29 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0002_classroom_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('role', models.CharField(choices=[('adviser', 'Adviser'), ('student', 'Student')], default='student', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='studenttype',
            name='custom_Type_For',
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentType',
        ),
        migrations.AddField(
            model_name='classroommember',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='classrooms.classroom'),
        ),
        migrations.AddField(
            model_name='classroommember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_classroommember_related', related_query_name='classrooms_classroommembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='classroommember',
            unique_together={('user', 'classroom')},
        ),
    ]
