# Generated by Django 3.2.8 on 2021-11-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_auto_20211112_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomresourcefolder',
            name='user',
        ),
    ]
