# Generated by Django 3.2.8 on 2021-12-02 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0003_alter_classroommember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.newuser'),
            preserve_default=False,
        ),
    ]
