# Generated by Django 3.2.8 on 2021-11-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_initial'),
        ('classrooms', '0004_remove_classroomresourcefolder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomresourcefolder',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_classroomresourcefolder_related', related_query_name='classrooms_classroomresourcefolders', to='institutions.institution'),
        ),
    ]
