# Generated by Django 3.2.8 on 2021-12-12 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        ('institutions', '0002_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='submission_files', to='workspaces.workspacefile'),
        ),
        migrations.AddField(
            model_name='recommendationresponse',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.recommendation'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.department'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.submission'),
        ),
    ]
