# Generated by Django 3.2.8 on 2021-12-01 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstitutionRecommendationResponse',
            new_name='RecommendationResponse',
        ),
        migrations.RenameModel(
            old_name='ClassroomSubmissionResponse',
            new_name='SubmissionResponse',
        ),
    ]
