# Generated by Django 3.2.8 on 2021-11-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20211121_2247'),
        ('submissions', '0002_auto_20211122_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsubmission',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, related_name='temporary_submission_files', to='workspaces.WorkspaceQuillFile'),
        ),
        migrations.AlterField(
            model_name='classroomsubmission',
            name='uploadfile',
            field=models.ManyToManyField(blank=True, null=True, related_name='submission_files', to='workspaces.WorkspaceUploadedFile'),
        ),
    ]
