# Generated by Django 3.2.8 on 2021-12-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20211201_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionresponse',
            name='responseStatus',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('revise', 'Revise'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
