# Generated by Django 3.2.8 on 2021-11-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20211121_2247'),
        ('submissions', '0003_auto_20211122_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomsubmission',
            name='file',
        ),
        migrations.AddField(
            model_name='classroomsubmission',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_submission_files', to='workspaces.workspacequillfile'),
        ),
        migrations.RemoveField(
            model_name='classroomsubmission',
            name='uploadfile',
        ),
        migrations.AddField(
            model_name='classroomsubmission',
            name='uploadfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='workspaces.workspaceuploadedfile'),
        ),
    ]
