# Generated by Django 3.2.8 on 2021-11-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_staff_department'),
        ('workspaces', '0006_alter_member_workspace'),
        ('submissions', '0004_auto_20211122_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('adviserResponse', models.CharField(choices=[('accepted', 'Accepted'), ('revise', 'Revise'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('institutionResponse', models.CharField(choices=[('accepted', 'Accepted'), ('revise', 'Revise'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('isSend', models.BooleanField(default=False)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_submission_files', to='workspaces.workspacequillfile')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('uploadfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='workspaces.workspaceuploadedfile')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-dateUpdated'],
            },
        ),
        migrations.RemoveField(
            model_name='institutionrecommendation',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institutionrecommendation',
            name='submission',
        ),
        migrations.DeleteModel(
            name='ClassroomSubmission',
        ),
        migrations.DeleteModel(
            name='InstitutionRecommendation',
        ),
    ]
