# Generated by Django 3.2.8 on 2021-11-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20211126_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submit', 'Submit')], default='pending', max_length=10),
        ),
    ]
