# Generated by Django 3.2.8 on 2021-11-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='institutionResponse',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('revise', 'Revise'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=10),
        ),
    ]
