# Generated by Django 3.2.8 on 2021-11-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_alter_submission_institutionresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='workspace',
        ),
    ]
