# Generated by Django 3.2.8 on 2021-12-01 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Admins of this chat.', related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
