# Generated by Django 3.2.8 on 2021-12-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatroom_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
