# Generated by Django 3.2.8 on 2021-12-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomsubscription',
            options={'ordering': ('-dateCreated',)},
        ),
        migrations.AlterModelOptions(
            name='institutionsubscription',
            options={'ordering': ('-dateCreated',)},
        ),
    ]
