# Generated by Django 3.2.8 on 2021-11-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20211114_2232'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_Email', models.EmailField(max_length=254)),
                ('payer_FullName', models.CharField(max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institutions.institution')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
