# Generated by Django 3.2.8 on 2021-12-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='limitations',
            field=models.BigIntegerField(blank=True, default=5000000000, null=True),
        ),
    ]
