# Generated by Django 3.2.8 on 2021-11-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
