# Generated by Django 3.2.8 on 2021-11-20 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_classroom_institution'),
        ('subscriptions', '0002_institutionsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsubscription',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom'),
        ),
    ]
