# Generated by Django 3.2.8 on 2021-11-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_alter_staff_unique_together'),
        ('subscriptions', '0003_alter_classroomsubscription_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan'),
        ),
    ]
