# Generated by Django 3.2.8 on 2021-11-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20211123_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='limitations',
            field=models.JSONField(blank=True, default={'storage': 5000000}, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
