# Generated by Django 3.2.8 on 2021-11-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_plan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='expiration',
        ),
    ]
