# Generated by Django 3.2.8 on 2021-11-24 04:42

from django.db import migrations, models
import subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20211124_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cover',
            field=models.ImageField(default='userProfile/coverDefault_pdrisr.jpg', upload_to=subscriptions.models.upload_to, verbose_name='Cover'),
        ),
    ]
