# Generated by Django 3.2.8 on 2021-11-24 04:44

from django.db import migrations, models
import subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_plan_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='limitations',
            field=models.JSONField(blank=True, default=subscriptions.models.Plan.storageSizeDefault, null=True),
        ),
    ]
