# Generated by Django 3.2.8 on 2021-11-14 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import institutions.models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10)),
                ('cover', models.ImageField(default='userProfile/coverDefault_pdrisr.jpg', upload_to=products.models.upload_to, verbose_name='Cover')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='userProfile/default_egry2i.jpg', upload_to=institutions.models.upload_to, verbose_name='Profile')),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-dateUpdated',),
                'abstract': False,
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('custom_Type_For', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.stafftype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions_staff_related', related_query_name='institutions_staffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to=institutions.models.upload_to)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'ordering': ('-institution__dateUpdated',),
            },
        ),
        migrations.CreateModel(
            name='InstitutionSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payerName', models.CharField(blank=True, max_length=255, null=True)),
                ('payerEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('paidDate', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institutions.institution')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.plan')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('published', 'published'), ('draft', 'draft')], default='draft', max_length=10)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'unique_together': {('name', 'institution')},
            },
        ),
    ]
