# Generated by Django 3.2.8 on 2021-11-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionsubscription',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institutionsubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='institutionverification',
            name='institution',
        ),
        migrations.DeleteModel(
            name='InstitutionResource',
        ),
        migrations.DeleteModel(
            name='InstitutionSubscription',
        ),
        migrations.DeleteModel(
            name='InstitutionVerification',
        ),
    ]
