# Generated by Django 3.2.8 on 2021-11-14 14:40

from django.db import migrations, models
import django.db.models.deletion
import institutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20211114_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to=institutions.models.upload_to)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'ordering': ('-institution__dateUpdated',),
            },
        ),
    ]
