# Generated by Django 3.2.8 on 2021-11-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institutionverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='status',
        ),
    ]
