# Generated by Django 3.2.8 on 2021-11-15 00:48

from django.db import migrations, models
import institutions.models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institutionverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftype',
            name='permissions',
            field=models.JSONField(default=members.models.defaultPermission),
        ),
        migrations.AlterField(
            model_name='institutionverification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=institutions.models.upload_verification),
        ),
        migrations.AlterField(
            model_name='stafftype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
