# Generated by Django 3.2.8 on 2021-12-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
