# Generated by Django 3.2.8 on 2021-11-08 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import institutions.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0004_remove_institution_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('permissions', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='institution',
            name='banner',
            field=models.ImageField(default='posts/coverDefault.jpg', upload_to=institutions.models.upload_to, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=institutions.models.upload_to, verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.newuser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.stafftype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomStaffType',
            fields=[
                ('stafftype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institutions.stafftype')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('institutions.stafftype',),
        ),
    ]
