# Generated by Django 3.2.8 on 2021-11-15 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20211115_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftype',
            name='custom_Type_For',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
    ]
