# Generated by Django 3.2.8 on 2021-11-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan'),
        ('institutions', '0005_auto_20211108_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.plan'),
        ),
        migrations.DeleteModel(
            name='InstitutionPlan',
        ),
    ]
