# Generated by Django 3.2.8 on 2021-11-15 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import institutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_alter_stafftype_custom_type_for'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionverification',
            options={'ordering': ('-dateModified',)},
        ),
        migrations.AddField(
            model_name='institutionverification',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutionverification',
            name='dateModified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='userProfile/default_egry2i.jpg', upload_to=institutions.models.upload_to_department, verbose_name='Profile')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'ordering': ('-dateModified',),
            },
        ),
    ]
