# Generated by Django 3.2.8 on 2021-11-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_auto_20211108_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='banner',
            new_name='cover',
        ),
    ]
