# Generated by Django 3.2.8 on 2021-12-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_alter_institution_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
