# Generated by Django 3.2.8 on 2021-11-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_auto_20211115_1303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'institution')},
        ),
    ]
