# Generated by Django 3.2.8 on 2021-12-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_alter_institution_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
