# Generated by Django 3.2.8 on 2021-11-15 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0007_alter_department_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('user', 'institution')},
        ),
    ]
