# Generated by Django 3.2.8 on 2021-11-11 06:34

from django.db import migrations, models
import institutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_rename_banner_institution_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='cover',
            field=models.ImageField(default='userProfile/coverDefault_pdrisr.jpg', upload_to=institutions.models.upload_to, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='image',
            field=models.ImageField(default='userProfile/default_egry2i.jpg', upload_to=institutions.models.upload_to, verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='institutionverification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=institutions.models.upload_to),
        ),
    ]
