# Generated by Django 3.2.8 on 2021-11-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_auto_20211111_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionverification',
            options={'ordering': ('-institution__dateUpdated',)},
        ),
        migrations.AddField(
            model_name='institutionsubscription',
            name='payerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institutionsubscription',
            name='payerName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
