# Generated by Django 3.2.8 on 2021-11-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_staff_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='institution',
            name='owner',
        ),
    ]
