# Generated by Django 3.2.8 on 2021-11-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_auto_20211129_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
