# Generated by Django 3.2.8 on 2021-12-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='redirectID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
