# Generated by Django 3.2.8 on 2021-11-14 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomresource',
            options={},
        ),
        migrations.AddField(
            model_name='classroomresourcequillfile',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomresourceuploadedfile',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomresourceuploadedfile',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classroomresourceuploadedfile',
            name='file',
            field=models.FileField(upload_to=files.models.upload_to),
        ),
        migrations.AlterUniqueTogether(
            name='classroomresource',
            unique_together={('classroom', 'name')},
        ),
    ]
