# Generated by Django 3.2.8 on 2021-11-15 14:24

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_institutionresource_institutionresourcefolder_institutionresourcequillfile_institutionresourceupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomresource',
            name='cover',
            field=models.ImageField(blank=True, default='userProfile/coverDefault_pdrisr.jpg', null=True, upload_to=files.models.upload_cover_to, verbose_name='Cover'),
        ),
        migrations.AddField(
            model_name='institutionresource',
            name='cover',
            field=models.ImageField(blank=True, default='userProfile/coverDefault_pdrisr.jpg', null=True, upload_to=files.models.upload_cover_to, verbose_name='Cover'),
        ),
    ]
