# Generated by Django 3.2.8 on 2021-12-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_alter_institution_creator'),
        ('resources', '0003_auto_20211201_1030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institutionresource',
            unique_together={('name', 'department')},
        ),
        migrations.RemoveField(
            model_name='institutionresource',
            name='institution',
        ),
    ]
