# Generated by Django 3.2.8 on 2021-11-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20211115_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomresource',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institutionresource',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
