# Generated by Django 3.2.8 on 2021-11-28 11:34

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20211115_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomresourcequillfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.upload_to),
        ),
        migrations.AddField(
            model_name='classroomresourcequillfile',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classroomresourceuploadedfile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionresourcequillfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.upload_to),
        ),
        migrations.AddField(
            model_name='institutionresourcequillfile',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institutionresourceuploadedfile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
