# Generated by Django 3.2.8 on 2021-11-29 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0006_auto_20211128_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('tags', models.CharField(blank=True, max_length=10, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=files.models.upload_to)),
                ('content', models.TextField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_classroomresourcefile_related', related_query_name='resources_classroomresourcefiles', to='resources.classroomresourcefolder')),
            ],
            options={
                'unique_together': {('name', 'folder')},
            },
        ),
        migrations.CreateModel(
            name='InstitutionResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('tags', models.CharField(blank=True, max_length=10, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=files.models.upload_to)),
                ('content', models.TextField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_institutionresourcefile_related', related_query_name='resources_institutionresourcefiles', to='resources.institutionresourcefolder')),
            ],
            options={
                'unique_together': {('name', 'folder')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classroomresourceuploadedfile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classroomresourceuploadedfile',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='classroomresourceuploadedfile',
            name='folder',
        ),
        migrations.AlterUniqueTogether(
            name='institutionresourcequillfile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='institutionresourcequillfile',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='institutionresourcequillfile',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='institutionresourceuploadedfile',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='institutionresourceuploadedfile',
            name='folder',
        ),
        migrations.DeleteModel(
            name='ClassroomResourceQuillFile',
        ),
        migrations.DeleteModel(
            name='ClassroomResourceUploadedFile',
        ),
        migrations.DeleteModel(
            name='InstitutionResourceQuillFile',
        ),
        migrations.DeleteModel(
            name='InstitutionResourceUploadedFile',
        ),
    ]
